# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='lemma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talgoxe.Lemma'),
        ),
        migrations.AddField(
            model_name='data',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talgoxe.Type'),
        ),
    ]
